services:
  - type: web
    name: nmt-english-bot
    runtime: python

    buildCommand: pip install -r requirements.txt

    startCommand: python main.py

    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: SUPABASE_URL
        sync: false

      - key: SUPABASE_KEY
        sync: false

      - key: ADMIN_IDS
        sync: false

      - key: WEBHOOK_BASE_URL
        sync: false

    healthCheckPath: /health

    autoDeploy: true
